#ifndef __G3507_HW_CONFIG_H
#define __G3507_HW_CONFIG_H

#include "ti/driverlib/dl_gpio.h" /* GPIO_Pin_x + GPIOA/B 原语，其余枚举值在 Enroll.c 展开时由 Enroll_Internal.h 提供 */

/*
 * G3507_hw_config.h 板级硬件映射宏
 * 只维护实际用到的端口/引脚/IOMUX，注册和查找都在这里完成。
 */

/* LED 板级映射 */
#define HW_LED_MAP(X) \
    X(LED1, GPIOB, DL_GPIO_PIN_14)\
    X(LED2, GPIOB, DL_GPIO_PIN_1)\
    X(LED3, GPIOB, DL_GPIO_PIN_0)\
    X(Buzzer1, GPIOA, DL_GPIO_PIN_7)

/* KEY 板级映射 */
#define HW_KEY_MAP(X) \
    X(KEY1, GPIOB, DL_GPIO_PIN_21)\
    X(KEY2, GPIOB, DL_GPIO_PIN_23)\
    X(KEY3, GPIOB, DL_GPIO_PIN_22)

/* USART0 板级映射 */
#define HW_USART0_TX_PORT GPIOA
#define HW_USART0_TX_PIN  DL_GPIO_PIN_10
#define HW_USART0_RX_PORT GPIOA
#define HW_USART0_RX_PIN  DL_GPIO_PIN_11

#define G3507_USART0_TX_IOMUX IOMUX_PINCM21
#define G3507_USART0_TX_FUNC  IOMUX_PINCM21_PF_UART0_TX
#define G3507_USART0_RX_IOMUX IOMUX_PINCM22
#define G3507_USART0_RX_FUNC  IOMUX_PINCM22_PF_UART0_RX

/* USART1 板级映射 */
#define HW_USART1_TX_PORT GPIOA
#define HW_USART1_TX_PIN  DL_GPIO_PIN_8
#define HW_USART1_RX_PORT GPIOA
#define HW_USART1_RX_PIN  DL_GPIO_PIN_9

#define G3507_USART1_TX_IOMUX IOMUX_PINCM19
#define G3507_USART1_TX_FUNC  IOMUX_PINCM19_PF_UART1_TX
#define G3507_USART1_RX_IOMUX IOMUX_PINCM20
#define G3507_USART1_RX_FUNC  IOMUX_PINCM20_PF_UART1_RX

/* USART2 板级映射 */
#define HW_USART2_TX_PORT GPIOB
#define HW_USART2_TX_PIN  DL_GPIO_PIN_17
#define HW_USART2_RX_PORT GPIOB
#define HW_USART2_RX_PIN  DL_GPIO_PIN_18

#define G3507_USART2_TX_IOMUX IOMUX_PINCM43
#define G3507_USART2_TX_FUNC  IOMUX_PINCM43_PF_UART2_TX
#define G3507_USART2_RX_IOMUX IOMUX_PINCM44
#define G3507_USART2_RX_FUNC  IOMUX_PINCM44_PF_UART2_RX

/* USART3 板级映射 */
#define HW_USART3_TX_PORT GPIOA
#define HW_USART3_TX_PIN  DL_GPIO_PIN_26
#define HW_USART3_RX_PORT GPIOA
#define HW_USART3_RX_PIN  DL_GPIO_PIN_25

#define G3507_USART3_TX_IOMUX IOMUX_PINCM59
#define G3507_USART3_TX_FUNC  IOMUX_PINCM59_PF_UART3_TX
#define G3507_USART3_RX_IOMUX IOMUX_PINCM55
#define G3507_USART3_RX_FUNC  IOMUX_PINCM55_PF_UART3_RX

#define HW_USART_MAP(X) \
    X(API_USART1, API_USART_CORE_UART0, HW_USART0_TX_PORT, HW_USART0_TX_PIN, HW_USART0_RX_PORT, HW_USART0_RX_PIN)\
    X(API_USART2, API_USART_CORE_UART1, HW_USART1_TX_PORT, HW_USART1_TX_PIN, HW_USART1_RX_PORT, HW_USART1_RX_PIN)\
    X(API_USART3, API_USART_CORE_UART2, HW_USART2_TX_PORT, HW_USART2_TX_PIN, HW_USART2_RX_PORT, HW_USART2_RX_PIN)\
    X(API_USART4, API_USART_CORE_UART3, HW_USART3_TX_PORT, HW_USART3_TX_PIN, HW_USART3_RX_PORT, HW_USART3_RX_PIN)

/* TIM 板级映射：
 * - API_TIM1 → TIMG0: 整个系统控制节拍 (1ms)
 */
#define HW_TIM_MAP(X) \
    X(API_TIM1, API_TIM_CORE_TIMG0)

/* PWM 板级映射：PB7=TIMG8 CCP1, PB15=TIMG8 CCP0。 */
#define G3507_PWM_CH0_PORT   GPIOB
#define G3507_PWM_CH0_PIN    DL_GPIO_PIN_7
#define G3507_PWM_CH0_IOMUX  IOMUX_PINCM24
#define G3507_PWM_CH0_FUNC   IOMUX_PINCM24_PF_TIMG8_CCP1

#define G3507_PWM_CH1_PORT   GPIOB
#define G3507_PWM_CH1_PIN    DL_GPIO_PIN_15
#define G3507_PWM_CH1_IOMUX  IOMUX_PINCM32
#define G3507_PWM_CH1_FUNC   IOMUX_PINCM32_PF_TIMG8_CCP0

#define HW_PWM_MAP(X) \
    X(API_PWM_TIM1, API_PWM_CH1, API_PWM_CORE_TIMG8, API_PWM_CORE_CCP0, G3507_PWM_CH0_PORT, G3507_PWM_CH0_PIN) \
    X(API_PWM_TIM1, API_PWM_CH2, API_PWM_CORE_TIMG8, API_PWM_CORE_CCP1, G3507_PWM_CH1_PORT, G3507_PWM_CH1_PIN)

/* ADC 板级映射*/
#define G3507_ADC0_CH4_PORT  GPIOB
#define G3507_ADC0_CH4_PIN   DL_GPIO_PIN_25
#define G3507_ADC0_CH4_IOMUX IOMUX_PINCM56

#define HW_ADC_MAP(X) \
    X(API_ADC1, API_ADC_CH4, G3507_ADC0_CH4_PORT, G3507_ADC0_CH4_PIN)

/* 软件 I2C1： GPIOB PB2(SCL)/PB3(SDA) */
#define HW_I2C1_SCL_PORT GPIOB
#define HW_I2C1_SCL_PIN  DL_GPIO_PIN_2
#define HW_I2C1_SCL_IOMUX IOMUX_PINCM15 /* PB2 */
#define HW_I2C1_SDA_PORT GPIOB
#define HW_I2C1_SDA_PIN  DL_GPIO_PIN_3
#define HW_I2C1_SDA_IOMUX IOMUX_PINCM16 /* PB3 */

/* 软件 I2C2：GPIOA PA1(SCL)/PA0(SDA) */
#define HW_I2C2_SCL_PORT GPIOA
#define HW_I2C2_SCL_PIN  DL_GPIO_PIN_1
#define HW_I2C2_SCL_IOMUX IOMUX_PINCM2  /* PA1 */
#define HW_I2C2_SDA_PORT GPIOA
#define HW_I2C2_SDA_PIN  DL_GPIO_PIN_0
#define HW_I2C2_SDA_IOMUX IOMUX_PINCM1  /* PA0 */

/* I2C 板级映射：注册 2 路软件 I2C。 */
#define HW_I2C_MAP(X) \
    X(API_I2C1, HW_I2C1_SCL_PORT, HW_I2C1_SCL_PIN, HW_I2C1_SDA_PORT, HW_I2C1_SDA_PIN, HW_I2C1_SCL_IOMUX, HW_I2C1_SDA_IOMUX) \
    X(API_I2C2, HW_I2C2_SCL_PORT, HW_I2C2_SCL_PIN, HW_I2C2_SDA_PORT, HW_I2C2_SDA_PIN, HW_I2C2_SCL_IOMUX, HW_I2C2_SDA_IOMUX)

/* 软件 SPI1：SCK=PB4，MOSI=PB5，MISO=PA29，CS=PB10 */
#define HW_SPI1_SCK_PORT  GPIOB
#define HW_SPI1_SCK_PIN   DL_GPIO_PIN_4
#define HW_SPI1_SCK_IOMUX IOMUX_PINCM17

#define HW_SPI1_MOSI_PORT GPIOB
#define HW_SPI1_MOSI_PIN  DL_GPIO_PIN_5
#define HW_SPI1_MOSI_IOMUX IOMUX_PINCM18

#define HW_SPI1_MISO_PORT GPIOA
#define HW_SPI1_MISO_PIN  DL_GPIO_PIN_29 //OLED实际没用到，随便给个空闲IO避免报错
#define HW_SPI1_MISO_IOMUX IOMUX_PINCM4

#define HW_SPI1_CS_PORT   GPIOB
#define HW_SPI1_CS_PIN    DL_GPIO_PIN_10
#define HW_SPI1_CS_IOMUX  IOMUX_PINCM27

/* SPI 板级映射：注册 1 路软件 SPI。 */
#define HW_SPI_MAP(X) \
        X(API_SPI1, HW_SPI1_CS_PORT, HW_SPI1_CS_PIN, \
            HW_SPI1_SCK_PORT, HW_SPI1_SCK_PIN, \
            HW_SPI1_MOSI_PORT, HW_SPI1_MOSI_PIN, \
            HW_SPI1_MISO_PORT, HW_SPI1_MISO_PIN, HW_SPI1_CS_IOMUX, HW_SPI1_SCK_IOMUX, HW_SPI1_MOSI_IOMUX, HW_SPI1_MISO_IOMUX)

/* OLED SPI 控制引脚定义：DC=PB11，RES=PB10 */
#define HW_OLED_DC_PORT  GPIOB
#define HW_OLED_DC_PIN   DL_GPIO_PIN_8
#define HW_OLED_DC_IOMUX IOMUX_PINCM25

#define HW_OLED_RES_PORT  GPIOB
#define HW_OLED_RES_PIN   DL_GPIO_PIN_6
#define HW_OLED_RES_IOMUX IOMUX_PINCM23

/* OLED SPI 控制引脚映射：注册 1 组 DC/RES。 */
#define HW_OLED_SPI_CTRL_MAP(X) \
	X(HW_OLED_DC_PORT, HW_OLED_DC_PIN, HW_OLED_RES_PORT, HW_OLED_RES_PIN)

/* MPU6050 INT 板级映射：PB4，对应 IOMUX_PINCM17。 */
#define HW_MPU6050_INT_PORT  GPIOA
#define HW_MPU6050_INT_PIN   DL_GPIO_PIN_28 //PCB V3.0实际没用到6050，随便给个空闲IO预留
#define HW_MPU6050_INT_IOMUX IOMUX_PINCM3

/* TB6612 板级映射：AIN1=PA14, AIN2=PA15, BIN1=PA12, BIN2=PA13。 */
#define HW_TB6612_AIN1_PORT   GPIOA
#define HW_TB6612_AIN1_PIN    DL_GPIO_PIN_12
#define HW_TB6612_AIN2_PORT   GPIOB
#define HW_TB6612_AIN2_PIN    DL_GPIO_PIN_13
#define HW_TB6612_BIN1_PORT   GPIOB
#define HW_TB6612_BIN1_PIN    DL_GPIO_PIN_11
#define HW_TB6612_BIN2_PORT   GPIOB
#define HW_TB6612_BIN2_PIN    DL_GPIO_PIN_9

#define HW_TB6612_MAP(X) \
    X(HW_TB6612_AIN1_PORT, HW_TB6612_AIN1_PIN, \
      HW_TB6612_AIN2_PORT, HW_TB6612_AIN2_PIN, \
      HW_TB6612_BIN1_PORT, HW_TB6612_BIN1_PIN, \
      HW_TB6612_BIN2_PORT, HW_TB6612_BIN2_PIN)

/* 编码器 1 */
#define HW_ENCODER1_A_PORT GPIOB
#define HW_ENCODER1_A_PIN  DL_GPIO_PIN_12
#define HW_ENCODER1_B_PORT GPIOB
#define HW_ENCODER1_B_PIN  DL_GPIO_PIN_16

/* 编码器 2 */
#define HW_ENCODER2_A_PORT GPIOA
#define HW_ENCODER2_A_PIN  DL_GPIO_PIN_13
#define HW_ENCODER2_B_PORT GPIOA
#define HW_ENCODER2_B_PIN  DL_GPIO_PIN_14

#define HW_ENCODER_MAP(X) \
    X(API_ENCODER_1, API_ENCODER_CORE_ENC0, \
      0U, HW_ENCODER1_A_PORT, HW_ENCODER1_A_PIN, \
      0U, HW_ENCODER1_B_PORT, HW_ENCODER1_B_PIN) \
    X(API_ENCODER_2, API_ENCODER_CORE_ENC1, \
      0U, HW_ENCODER2_A_PORT, HW_ENCODER2_A_PIN, \
      0U, HW_ENCODER2_B_PORT, HW_ENCODER2_B_PIN)

/* GrayADC 灰度传感器地址引脚映射：AD0=PB17, AD1=PB18, AD2=PB19 */
#define HW_GRAY_ADC_AD0_PORT  GPIOB
#define HW_GRAY_ADC_AD0_PIN   DL_GPIO_PIN_19
#define HW_GRAY_ADC_AD1_PORT  GPIOB
#define HW_GRAY_ADC_AD1_PIN   DL_GPIO_PIN_24
#define HW_GRAY_ADC_AD2_PORT  GPIOA
#define HW_GRAY_ADC_AD2_PIN   DL_GPIO_PIN_24

#define HW_GRAY_ADC_MAP(X) \
    X(HW_GRAY_ADC_AD0_PORT, HW_GRAY_ADC_AD0_PIN, \
      HW_GRAY_ADC_AD1_PORT, HW_GRAY_ADC_AD1_PIN, \
      HW_GRAY_ADC_AD2_PORT, HW_GRAY_ADC_AD2_PIN)

/* 当前板子上注册了 3 个LED + 1 个蜂鸣器 */
#define HW_LED_COUNT    4U
/* 当前板子上注册了 3 个按键 */
#define HW_KEY_COUNT    3U
/* 当前板子上注册了 4 路 USART */
#define HW_USART_COUNT  4U
/* 当前板子上注册了 2 路 PWM输出通道*/
#define HW_PWM_COUNT    2U
/* 当前板子上注册了 1 路 TIM中断 */
#define HW_TIM_COUNT   1U
/* 当前板子上注册了 1 路 ADC */
#define HW_ADC_COUNT  1U
/* 当前板子上注册了 2 路软件 I2C */
#define HW_I2C_COUNT  2U
/* 当前板子上注册了 1 路软件 SPI */
#define HW_SPI_COUNT  1U
/* 当前板子上注册了 1 组 OLED SPI 控制引脚 */
#define HW_OLED_SPI_CTRL_COUNT  1U
/* 当前板子上注册了 1 路 MPU6050 INT 引脚 */
#define HW_MPU6050_COUNT 1U
/* 当前板子上注册了 1 路 TB6612 电机驱动 */
#define HW_TB6612_COUNT 1U
/* 当前板子上注册了 2 个编码器 */
#define HW_ENCODER_COUNT  2U
/* 当前板子上注册了 1 路 GrayADC 灰度传感器 */
#define HW_GRAY_ADC_COUNT  1U

#endif /* __G3507_HW_CONFIG_H */
